### ISSUE TITLE
Multivariate Time Series Model for forecasting including Cross-Validation Method (ISLR, Chapter 5 and 6)

### ISSUE THREAD

**Issue by FienThibau** [Multinational-Minds/BDA#3]
**Multivariate regression**
https://medium.com/pew-research-center-decoded/using-fixed-and-random-effects-models-for-panel-data-in-python-a795865736ab
**Time series**
https://www.mathworks.com/discovery/time-series-regression.html
https://www.analyticsvidhya.com/blog/2018/09/multivariate-time-series-guide-forecasting-modeling-python-codes/
https://www.mathworks.com/help/econ/examples/time-series-regression-i-linear-models.html
https://www.kaggle.com/kashnitsky/topic-9-part-1-time-series-analysis-in-python
**Multivariate time series analysis**
http://www.eco.uc3m.es/~jgonzalo/teaching/TecnicasEconometricas/WooldridgeCh10-12.pdf
https://analyticsindiamag.com/multivariate-time-series-analysis-for-data-science-rookies/
https://towardsdatascience.com/prediction-task-with-multivariate-timeseries-and-var-model-47003f629f9
https://blog.edugrad.com/forecasting-and-modeling-with-a-multivariate-time-series-in-python/
https://machinelearningmastery.com/how-to-develop-machine-learning-models-for-multivariate-multi-step-air-pollution-time-series-forecasting/
K-fold CV:
https://towardsdatascience.com/machine-learning-algorithms-part-14-cross-validation-and-ridge-regression-example-in-python-2d9e0c4de875

**Comment by SDanciu** [comment]
just info to help me analyze:
Suppose we have to forecast the temperate, dew point, cloud percent, etc. for the next two months using data from the last two years. One possible method is to keep the data for the last two months aside and train the model on the remaining 22 months.

**Comment by pietergobin** [comment]
fuck this shit I'm out, Imma get the fuck outta here
